sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Whlkhvig6I+JOYjmE62Uu84/7MAFBXPJvo9jK+BfXbUsN5qZAHS56Kj/g0YqyPgy5SSZxRIlAHubT9tgUD5Oi4FpJKNjrhFlqivP6HfLwhx9HZN2Vbo67XPzz/Npxh5+EqrUY7oXFB8ZJBwbpvgTR8ZqTVPlAWSy/04fRhveWN/mCvPyBw7s1OI9gsB09OzJgTuFGjoU3eH0UzrHKljJWdGFhzq05lhKTRFLdqqzHYyjjSKVeVVOLp99HVGkt96sX4uEkedPh0h33J9+4thIzq5vuOOSreiUzpDFwX/jDW20RpouEAum7ek05LmzQqweDwHwa+V8S+mizkX++zcK1s5xW908YtMU147kkjSOD0VbQHGMHhY98ldNJoP1Dg1aJnMmo5LXpBJ2HbRTDS3XgWIxzfJWC4zJL7jqSK4pwIJOGEC0h4kBiVK5K2ZiqTkruqPN6uGCGXbL+1w2gWL+YFv83VjmMwRPo03hFZkk2g7bO8Ht6AVsTY+Cnn5V8USZzWtme1Ab7G7BR1DXFgqwLEzT+ikbZ2gYy6t7cBZzgEV6VJklqP8dfmPnMgZwSDO+CF+IjkJNxIjT94MF1BoqkjmBi8MKNUs4ZFTmCOQpQu2eyl34O9Ok8DyAun3p93zF3aKyYP5/lYzYgxJf/oSh45YQOkvnfDXAbWw0V3II3jU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Two-Brothers_1380
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy